{
    "name":"Shop Management",
    "version":"19.0.1.0.1",
    "category":"Sales",
    "summary":"Simple shop course example for junior odoo developer.",
    "depends":['product'],
    "data":[
        'security/ir.model.access.csv',
        'security/shop_security.xml',
        'data/ir_sequence.xml',
        'views/shop_item_views.xml',
        'views/shop_menu_views.xml',
        'data/shop_item_tag.xml',
        'data/shop_cron_data.xml',
        'reports/stop_item_report.xml',
    ],
    "installable":True,
    "application":True,
    "license": "LGPL-3",
}